<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="/admin">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Suporte</li>
</ol>
<div class="row">
    <div class="col-12">
        <h1>Suporte</h1>
        <p>Log de tickets</p>
        <hr>
    </div>
    <div class="col-md-12">
        <div class="card mt-4">
            <div class="card-header">Log de tickets</div>
            <div class="card-body">
                <table class="table table-striped table-bordered dt-responsive nowrap datatable" style="width:100%">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Usuário</th>
                        <th>Nº do Pedido</th>
                        <th>Assunto</th>
                        <th>Status</th>
                        <th>Visualizar</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?= $this->tickets->logs() ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>