<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="/admin">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Suporte</li>
</ol>
<div class="row">
    <div class="col-12">
        <h1>Suporte</h1>
        <p>Mensagens prontas</p>
        <hr>
    </div>
    <div class="col-md-6">
        <div class="card mt-4">
            <div class="card-header">Criar uma mensagem</div>
            <div class="card-body">
                <form method="post" id="createMessage">
                    <div class="from-group">
                        <label>Identificador</label>
                        <input class="form-control" name="name">
                        <br>
                    </div>
                    <div class="from-group">
                        <label>Mensagem</label>
                        <textarea class="form-control" name="body" rows="7" style="resize: none"></textarea>
                    </div>
                    <br>
                    <button class="btn btn-primary">Salvar mensagem</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card mt-4">
            <div class="card-header">Mensagens feitas</div>
            <div class="card-body">
                <table class="table table-striped table-bordered dt-responsive nowrap datatable" style="width:100%">
                    <thead>
                    <tr>
                        <th>Identificador</th>
                        <th>Ação</th>
                    </tr>
                    </thead>
                    <tbody>
                        <?= $this->tickets->autoTable() ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>