<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Painel de Controle</title>

    <link href="<?= APP_ROOT ?>/app/content/admin/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?= APP_ROOT ?>/app/content/admin/assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="<?= APP_ROOT ?>/app/content/admin/assets/css/sb-admin.css" rel="stylesheet">
</head>
<body class="bg-dark">

<?= $this->render(); ?>

<script src="<?= APP_ROOT ?>/app/content/admin/assets/vendor/jquery/jquery.min.js"></script>
<script src="<?= APP_ROOT ?>/app/content/admin/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="<?= APP_ROOT ?>/app/content/admin/assets/vendor/jquery-easing/jquery.easing.min.js"></script>
<script src="<?= APP_ROOT ?>/app/content/admin/assets/javascript/functions.js"></script>
</body>

</html>