<div class="container">
    <div class="content">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/"><i class="ion-home"></i></a></li>
                <li class="breadcrumb-item active" aria-current="page">Punições</li>
            </ol>
        </nav>
        <div class="row">
            <div class="col-md-9">
                <h1 class="m-0">Punições</h1>
                <h3 class="text-muted"><small>Fique por dentro das punições recentes</small></h3>
                <br>
                <?php
                if(!isset($_POST[$this->inputs['search']]) || empty($_POST[$this->inputs['search']])):
                    echo $this->punish->recents();
                else:
                    if($this->forms->checkValid($_POST)):
                        $value = $_POST[$this->inputs['search']]
                        ?> 
                        <div class="row">
                            <div class="col-md-2">
                                <img src="https://minotar.net/helm/<?= htmlspecialchars(strip_tags(trim($value)), ENT_QUOTES, 'UTF-8') ?>/500.png" class="img-fluid">
                                <br>
                                <p class="text-center text-muted"><b><span><?= htmlspecialchars(strip_tags(trim($value)), ENT_QUOTES, 'UTF-8') ?></span></b></p>
                            </div>
                            <div class="col-md-10">
                                <h3>Resultados da pesquisa:</h3>
                                <hr>
                                <?= $this->punish->search(htmlspecialchars(strip_tags(trim($value)), ENT_QUOTES, 'UTF-8')); ?>
                            </div>
                        </div>
                        <?php $this->forms->formNames(['search'], true); endif ?>
                <?php endif ?>
            </div>
            <div class="col-md-3">
                <form method="post" id="punishCheck">
                    <input type="hidden" name="<?= $this->tokenID ?>" value="<?= $this->tokenVALUE ?>">
                    <label style="position: relative; width: 100%"><input class="form-control p-2 mb-4" name="<?= $this->inputs['search'] ?>" placeholder="Pesquisar por um jogador..."> <i style="position: absolute; right: 10px; top: 8px; font-size: 18px; color: #000;" class="ion-android-search"></i></label>
                </form>
                <div class="card mb-4">
                    <div class="card-block p-3">
                        <p class="m-0 text-center"><b style="font-size: 2.4em;"><?= $this->punish->row() ?></b></p>
                        <p class="text-center m-0 text-muted">punições aplicadas</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>