<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="/admin">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Configurações</li>
    <li class="breadcrumb-item active">Banco de Dados</li>
</ol>
<div class="row">
    <div class="col-12">
        <h1>Banco de Dados</h1>
        <p>Banco de dados do servidor</p>
        <hr>
    </div>
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                AuthMe
            </div>
            <div class="card-body">
                <form method="post" class="setDatabase">
                    <input type="hidden" name="type" value="authme">
                    <div class="form-group">
                        <label>Host:</label>
                        <input name="host" class="form-control" value="<?= $this->settings->printDatabases('authme')->host ?>">
                    </div>
                    <div class="form-group">
                        <label>Usuário:</label>
                        <input name="username" class="form-control" value="<?= $this->settings->printDatabases('authme')->username ?>">
                    </div>
                    <div class="form-group">
                        <label>Senha:</label>
                        <input name="password" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Banco de Dados:</label>
                        <input name="database" class="form-control" value="<?= $this->settings->printDatabases('authme')->database ?>">
                    </div>
                    <button class="btn btn-primary btn-block">ATUALIZAR</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                LiteBans
            </div>
            <div class="card-body">
                <form method="post" class="setDatabase">
                    <input type="hidden" name="type" value="litebans">
                    <div class="form-group">
                        <label>Host:</label>
                        <input name="host" class="form-control" value="<?= $this->settings->printDatabases('litebans')->host ?>">
                    </div>
                    <div class="form-group">
                        <label>Usuário:</label>
                        <input name="username" class="form-control" value="<?= $this->settings->printDatabases('litebans')->username ?>">
                    </div>
                    <div class="form-group">
                        <label>Senha:</label>
                        <input name="password" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>Banco de Dados:</label>
                        <input name="database" class="form-control" value="<?= $this->settings->printDatabases('litebans')->database ?>">
                    </div>
                    <button class="btn btn-primary btn-block">ATUALIZAR</button>
                </form>
            </div>
        </div>
    </div>
</div>