<section class="container">
    <div id="content">
        <div class="row">
        <div class="col-md-9">
                <div class="card">
                    <div class="card-body">
                    <?= $this->staff->show() ?>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="card text-center" style="padding: 10px; ">
                <h4>ENTRE PARA<br> <b>NOSSA EQUIPE</b></h4>
                        <p class="text-center"><button onclick="goTo('https://bit.ly/2JrhhyL')" style="margin-top: 10px;padding: 5px 10px; border-radius: 4px; background-color:#7a6fbf; color: #FFF; font-weight: 600;">Fazer teste</button></p>
                </div>
            </div>
            
        </div>
    </div>
</section>