<section id="dashboard">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Dashboard</a>
        </li>
        <li class="breadcrumb-item active">Início</li>
    </ol>
    <?php if($this->permissions->node('dashboard')): ?>
    <div class="row">
        <div class="col-xl-4 col-sm-6 mb-3">
            <div class="card text-white bg-primary o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fa fa-fw fa-comments"></i>
                    </div>
                    <div class="mr-5"><?= $this->posts->count() ?> Postagens</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="/admin/site/postagens/gerenciar">
                    <span class="float-left">Ir para as postagens</span>
                    <span class="float-right">
                        <i class="fa fa-angle-right"></i>
                    </span>
                </a>
            </div>
        </div>
        <div class="col-xl-4 col-sm-6 mb-3">
            <div class="card text-white bg-success o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fa fa-fw fa-shopping-cart"></i>
                    </div>
                    <div class="mr-5"><?= $this->transactions->salesCount() ?> Vendas</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="/admin/loja/transacoes">
                    <span class="float-left">Ir para transações</span>
                    <span class="float-right">
                        <i class="fa fa-angle-right"></i>
                    </span>
                </a>
            </div>
        </div>
        <div class="col-xl-4 col-sm-6 mb-3">
            <div class="card text-white bg-danger o-hidden h-100">
                <div class="card-body">
                    <div class="card-body-icon">
                        <i class="fa fa-fw fa-support"></i>
                    </div>
                    <div class="mr-5"><?= $this->tickets->countOpeneds() ?> Ticket(s) aberto(s)</div>
                </div>
                <a class="card-footer text-white clearfix small z-1" href="/admin/suporte">
                    <span class="float-left">Ir para o suporte</span>
                    <span class="float-right">
                        <i class="fa fa-angle-right"></i>
                    </span>
                </a>
            </div>
        </div>
    </div>
    <div class="card mb-3">
        <div class="card-header">
            <i class="fa fa-area-chart"></i>
            Gráfico de ganhos <span class="text-muted">(últimos 7 dias)</span>
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-sm-9 my-auto">
                    <canvas id="myAreaChart" width="100%" height="30"></canvas>
                </div>
                <div class="col-sm-3 text-center my-auto">
                    <div class="h4 mb-0 text-warning">R$<?= number_format($this->transactions->getEarnsInDate(date("Y-m-d")), 2, ',', '.') ?></div>
                    <div class="small text-muted">Ganhos hoje</div>
                    <hr>
                    <div class="h4 mb-0 text-primary">R$<?= number_format($this->transactions->getWeekEarns(), 2, ',', '.') ?></div>
                    <div class="small text-muted">Últimos 7 dias</div>
                    <hr>
                    <div class="h4 mb-0 text-success">R$<?= number_format($this->transactions->getTotalEarns(), 2, ',', '.') ?></div>
                    <div class="small text-muted">Total ganho</div>
                </div>
            </div>
            <script>
                <?php

                    $days = $this->transactions->getDateInDays(7);
                    $days = array_reverse($days);
                    $labels = '';
                    $data   = '';
                    foreach ($days as $day => $value)
                    {
                        $labels.='"'.strftime("%d %B", strtotime($value)).'", ';
                        $data.= $this->transactions->getEarnsInDate($value).', ';
                    }
                ?>
                scripts.push(function () {
                    var ctx = document.getElementById("myAreaChart");
                    var myLineChart = new Chart(ctx, {
                        type: 'line',
                        data: {
                            labels: [<?= $labels ?>],
                            datasets: [{
                                label: "Ganhos",
                                lineTension: 0.3,
                                backgroundColor: "rgba(2,117,216,0.2)",
                                borderColor: "rgba(2,117,216,1)",
                                pointRadius: 5,
                                pointBackgroundColor: "rgba(2,117,216,1)",
                                pointBorderColor: "rgba(255,255,255,0.8)",
                                pointHoverRadius: 5,
                                pointHoverBackgroundColor: "rgba(2,117,216,1)",
                                pointHitRadius: 20,
                                pointBorderWidth: 2,
                                data: [<?= $data ?>],
                            }],
                        },
                        options: {
                            scales: {
                                xAxes: [{
                                    time: {
                                        unit: 'date'
                                    },
                                    gridLines: {
                                        display: false
                                    },
                                    ticks: {
                                        maxTicksLimit: 7
                                    }
                                }],
                                yAxes: [{
                                    ticks: {
                                        min: 0,
                                        maxTicksLimit: 5
                                    },
                                    gridLines: {
                                        color: "rgba(0, 0, 0, .125)",
                                    }
                                }],
                            },
                            legend: {
                                display: false
                            }
                        }
                    });
                });
            </script>
        </div>
        <div class="card-footer small text-muted">
            Atualizado agora mesmo
        </div>
    </div>
    <div class="card mb-3">
        <div class="card-header">
            <i class="fa fa-table"></i> Últimas transações</div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Usuário</th>
                        <th>Iniciado em</th>
                        <th>Valor à receber</th>
                        <th>Status</th>
                    </tr>
                    </thead>
                    <tbody>
                        <?= $this->transactions->todayTable() ?>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer small text-muted">Atualizado agora mesmo</div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="mb-0 mt-4">
                <i class="fa fa-newspaper-o"></i> Postagens recentes
            </div>
            <hr class="mt-2">
            <div class="row">
                <?= $this->posts->recents() ?>
            </div>
        </div>
    </div>
    <?php else: ?>
    <div class="col-md-12">
        <h1>Dashboard</h1>
        <p class="text-muted">Seja bem vindo ao painel de administração do site.</p>
    </div>
    <?php endif ?>
</section>