<div class="container">
    <div id="content">
        <div class="card">
            <div class="row">
                <div class="col-md-4 mr-auto ml-auto">
                    <h1>Login</h1>
                    <div class="alert alert-danger" style="display: none;"></div>
                    <div class="alert alert-success" style="display: none;"></div>
                    <form method="post" id="loginAccount">
                        <input type="hidden" name="<?= $this->tokenID ?>" value="<?= $this->tokenVALUE ?>">
                        <div class="form-group">
                            <label for="nickname">Usuário</label>
                            <input class="form-control" name="<?= $this->inputs['username'] ?>" id="nickname" maxlength="16" placeholder="Nick utilizado no servidor">
                        </div>
                        <div class="form-group">
                            <label for="password">Senha</label>
                            <input class="form-control" name="<?= $this->inputs['password'] ?>" id="password"  type="password" placeholder="Senha">
                        </div>
                        <div class="form-group">
                            <label><input type="checkbox" name="<?= $this->inputs['mode'] ?>"> Permanecer logado?</label>
                        </div>
                        <button class="btn btn-block btn-primary" style="margin-bottom: 15px; background-color: #7A6FBF; border: 0 !important;">ENTRAR</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>